Add Search Functionality and Fix Project List Display Bug
Catrobat/Paintroid-Flutter pull request #105
Opened 2024-12-31 20:04 UTC by chetanr25

### Ticket 
JIRA Ticket - [PAINTROID-490](https://catrobat.atlassian.net/jira/software/c/projects/PAINTROID/issues/PAINTROID-490?filter=allissues&jql=project%20%3D%20%22PAINTROID%22%0Aand%20status%20%3D%20%22Ready%20For%20Development%22%0Aand%20assignee%20%3D%20empty%0Aand%20type%20in%20%28Bug%2C%20Story%2C%20Task%29%0Aand%20labels%20%3D%20Flutter%0AORDER%20BY%20created%20DESC)

This PR introduces a search functionality to the LandingPage that allows users to search for projects by name. The search feature includes a search toggle button and a search text field. When the search button is pressed, it hides the ProjectPreview and focuses on just the list of projects. The FloatingActionButton also hides as we go into search mode.

## New Features and Enhancements
#### Added search bar functionality to search projects by name 
### Changes
1. **Added `SearchToggleButton` Component:**
   - Created a new `SearchToggleButton` component that toggles between a search icon and a close icon based on the search state.
   - The button triggers the start and end of the search functionality.

2. **Added `SearchTextField` Component:**
   - Created a new `SearchTextField` component that provides a text input field for users to enter their search queries.
   - The text field updates the search query state and filters the project list accordingly.

3. **Updated `LandingPage` to Integrate Search Functionality:**
   - Added search functionality in the `LandingPage` component.
   - Integrated the `SearchToggleButton` and `SearchTextField` components into the `AppBar's title` of the `LandingPage`.
   - Implemented logic to filter the project list based on the search query.
   - Modified the `LandingPage` to hide `ProjectPreview` and `FloatingActionButton` when in search mode.

## Refactorings and Bug Fixes
- Fixed Bug with Project List Display:
  - Resolved an issue where only `n-1` projects were displayed when `n` projects were saved.
Removed unnecessary `index != 0` condition to ensure all saved projects are visible.

https://github.com/user-attachments/assets/f55bdd57-0781-485b-ac82-ceb3bad47cc7

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Add the link to the ticket in Jira in the description of the PR
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines (Wiki)
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Add new information to the [Wiki](https://github.com/Catrobat/Paintroid-Flutter/wiki)

2025-01-25 18:10 UTC, Lenkomotive requested changes
Hey! Good work! 

Functionality wise it looks really good, nice job!

Some points:

- The landing page uses setState for state management, which was likely the initial implementation approach. Since we now use Riverpod throughout the app, refactoring the landing page to use Riverpod would improve consistency and could be a fun challenge.
- We are striving to work with TDD (Test-Driven Development) as much as possible. I understand that it’s not always easy to strictly adhere to TDD. In cases where it is not feasible, please make sure to add new widget tests or integration tests afterward, especially for new implementations.

If you got any questions feel free to tag me or other contributors! Cheers 🌞

2025-01-25 19:40 UTC, chetanr25 commented
Thank you for the feedback!

I wanted to ensure the feature in this PR meets expectations before proceeding further with adding tests. 
I’ll refactor the landing page to use Riverpod for consistency and will also work on adding the necessary tests. I’ll send a follow-up PR soon.

Appreciate your guidance!

2025-01-26 07:13 UTC, chetanr25 commented
I have merged PR #107 to the current PR

2025-01-26 07:18 UTC, chetanr25 commented
- Migrated landing page state management from setState to Riverpod providers
- Created `search_filter_sort_provider.dart` file in `lib/core/providers/object` folder
- Optimized loading experience by conditionally showing progress indicator
- Removed redundant setState calls and local state variables

I am working on writing test files

2025-01-31 12:18 UTC, chetanr25 commented
Added comprehensive test coverage for:
- Search bar visibility and toggle behavior
- Project filtering based on search queries
- Sort options menu display and selection
- FAB visibility during search mode

All tests are passing. Please let me know if any changes are needed!
PR for ticket JIRA Ticket - [PAINTROID-490](https://catrobat.atlassian.net/jira/software/c/projects/PAINTROID/issues/PAINTROID-490?filter=allissues&jql=project%20%3D%20%22PAINTROID%22%0Aand%20status%20%3D%20%22Ready%20For%20Development%22%0Aand%20assignee%20%3D%20empty%0Aand%20type%20in%20%28Bug%2C%20Story%2C%20Task%29%0Aand%20labels%20%3D%20Flutter%0AORDER%20BY%20created%20DESC) is ready for review

2025-03-04 07:32 UTC, chetanr25 commented
@Lenkomotive The implementation is complete and working as expected. Please let me know if any changes are required.
The PR is ready to be merged

2025-05-15 15:35 UTC, juliajulie95 commented
@Lenkomotive please check

2025-05-16 12:09 UTC, Lenkomotive commented
SORRY FOR THE LATE RESPONSE! The Flutter version was updated in the meantime, could you @chetanr25 please merge the current master into your PR and fix the deprecations please? I will checkout the PR then again :D

2026-02-05 15:06 UTC, closed without merging