PAINTROID-458: Fix multi-touch brush tool behaviour
Catrobat/Paintroid-Flutter pull request #12
Opened 2022-11-08 11:10 UTC by davidmoling

Ticket: https://jira.catrob.at/browse/PAINTROID-458

2022-11-22 16:02 UTC, CodeChamp-SS requested changes

2022-11-22 16:02 UTC, CodeChamp-SS commented on lib/workspace/src/ui/drawing_canvas.dart
> +            multiScaleInProgress = true; // prevent first dot draw bug
is this `multiScaleInProgress` variable required? Can't check directly with the if condition in `onScaleEnd`? 🤔

2022-11-22 16:02 UTC, CodeChamp-SS commented on lib/workspace/src/ui/drawing_canvas.dart
> +            if (!multiScaleInProgress) {
```suggestion
            if (details.pointerCount == 1) {
```

2022-11-25 14:57 UTC, davidmoling commented on lib/workspace/src/ui/drawing_canvas.dart
> +            multiScaleInProgress = true; // prevent first dot draw bug
yes, it was tried without, but then a first dot is drawn when scaling. This line disables drawing until it is determined for sure that it is a single touch.

2022-11-25 15:13 UTC, davidmoling commented on lib/workspace/src/ui/drawing_canvas.dart
> +            multiScaleInProgress = true; // prevent first dot draw bug
does not work unfortunately with the suggested way, feel free to try it out

2022-11-25 15:13 UTC, davidmoling commented on lib/workspace/src/ui/drawing_canvas.dart
> +            if (!multiScaleInProgress) {
see comment above

2022-11-25 15:17 UTC, CodeChamp-SS commented on lib/workspace/src/ui/drawing_canvas.dart
> +            multiScaleInProgress = true; // prevent first dot draw bug
oh ok

2022-11-25 15:19 UTC, CodeChamp-SS approved these changes
LGTM

2023-04-03 16:38 UTC, merged