PAINTROID-654 : Remove tests from exluded folders and fix issues
Catrobat/Paintroid-Flutter pull request #33
Opened 2023-08-21 14:42 UTC by bakicelebi

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-10-11 17:40 UTC, Lenkomotive commented on test/fixture/image/test1.png
Is this needed?

2023-10-11 17:46 UTC, Lenkomotive requested changes
see comment

2023-11-29 20:13 UTC, Lenkomotive approved these changes

2023-12-11 09:51 UTC, juliajulie95 commented
@bakicelebi Why is device info plus added?
I don't see any import for it here

2023-12-27 08:55 UTC, merged