PAINTROID-679 Addition of Tooltips
Catrobat/Paintroid-Flutter pull request #39
Opened 2023-12-27 15:22 UTC by bhav-khurana

## Ticket
[PAINTROID 701](https://jira.catrob.at/browse/PAINTROID-701)

## New Features and Enhancements
Adds tooltips at places like `New Image` and the `Import Image` buttons and the like to enhance user experience and let the user know the functionality of each of the buttons clearly.

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2023-12-28 09:58 UTC, bhav-khurana commented
@juliajulie95 @bakicelebi Can you please review this?

2023-12-29 11:28 UTC, bakicelebi requested changes
Thanks for showing interest in our project! 

1. Requested small changes so that its consistent with the rest of the app.
2. Please close this PR and create a new one with your ticket id as the branch name ```PAINTROID-701```.

2023-12-29 11:28 UTC, bakicelebi commented on lib/ui/landing_page/landing_page.dart
> +            hint: 'Import Image',
Lets rename  this to ```Load image```for consistency with the overflow menu

2023-12-29 11:28 UTC, bakicelebi commented on lib/ui/landing_page/landing_page.dart
> +            hint: 'New Image',
Same here ``New image```

2023-12-29 11:28 UTC, bakicelebi commented on lib/ui/drawing_space/bottom_brush_tool_options.dart
> +              hint: 'Round',
```Round stroke``` would be clearer I think

2023-12-29 11:28 UTC, bakicelebi commented on lib/ui/drawing_space/bottom_brush_tool_options.dart
> +              hint: 'Square',
Similarly ```Square stroke```

2023-12-29 11:37 UTC, bhav-khurana commented
Sure! I'm closing this PR and creating a new one with the requested changes.

2023-12-29 11:37 UTC, closed without merging

2023-12-30 09:47 UTC, juliajulie95 commented
No need to close it next time :) Just push your changes and let us know when you're done :)

2023-12-30 09:50 UTC, bhav-khurana commented
@juliajulie95
Actually, @bakicelebi suggested me to change the branch name to the JIRA ticket id. So I had to close it as requested by him