Paintroid 448 Flutter: Create Save/ Load functionality
Catrobat/Paintroid-Flutter pull request #4
Opened 2022-07-09 13:40 UTC by krispykalsi

Ticket: https://jira.catrob.at/browse/PAINTROID-448

2022-08-09 17:49 UTC, juliajulie95 requested changes

2022-08-09 17:49 UTC, juliajulie95 commented on README.md
> +5. Build supporting files - `flutter pub run build_runner build`
Use shell file as discussed

2022-08-09 18:49 UTC, ThorstenBandel commented
Tested with: Android 6 to 12

2022-08-10 14:34 UTC, juliajulie95 approved these changes

2022-08-10 14:41 UTC, merged