PAINTROID-491: Add Rename project option
Catrobat/Paintroid-Flutter pull request #45
Opened 2024-01-04 17:35 UTC by msesko

Implement the functionality for renaming the project from the landing page itself. Add the Rename option in the ProjectOverflowMenu. (The Menu for each project). When pressing the rename option a popup window will open with the title "Rename project" and a textfield with the current name of the project. The buttons in the popup will be "Rename" and "Cancel" 

Jira ticket: [PAINTROID-662](https://jira.catrob.at/browse/PAINTROID-491)

## New Features and Enhancements
- Add the Rename option in the ProjectOverflowMenu (The Menu for each project)
- When pressing the rename option a popup window will open with the title "Rename project" and a textfield with the current name of the project.
- The buttons in the popup "Rename" and "Cancel" 
- Check that textfield not empty
- Check to not name the project the same as some other project
## Refactorings and Bug Fixes
- /

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-01-05 08:50 UTC, rkverma2022 commented
Hi, I am willing to implement "Add Rename" #45 
I am excited to do this. Please provide me guidelines, as I understand where this particular file or code is... and contribution guidelines too.

Thank You

2024-01-05 08:50 UTC, rkverma2022 commented
Hi, I am willing to implement "Add Rename" #45 
I am excited to do this. Please provide me guidelines, as I understand where this particular file or code is... and contribution guideline too.

2024-01-25 14:25 UTC, juliajulie95 commented
> Hi, I am willing to implement "Add Rename" #45 I am excited to do this. Please provide me guidelines, as I understand where this particular file or code is... and contribution guidelines too.
> 
> Thank You

As you can see this ticket is already finished.
Please check our jira board for open tickets:
https://jira.catrob.at/secure/RapidBoard.jspa?rapidView=138&view=detail&selectedIssue=PAINTROID-491

2024-03-04 15:59 UTC, juliajulie95 commented
Please resolve conflicts @msesko

2024-03-06 21:40 UTC, msesko commented
> Please resolve conflicts @msesko

done

2024-03-31 17:14 UTC, bakicelebi requested changes

2024-03-31 17:14 UTC, bakicelebi commented on packages/features/landing_page_screen/lib/src/components/project_overflow_menu.dart
> +      // Check if any project in the database already has the new name
No comments.

2024-03-31 17:14 UTC, bakicelebi commented on packages/features/landing_page_screen/lib/src/components/project_overflow_menu.dart
> +        throw Exception('A project with the name "$name" already exists.');
Exception? Please show a toast and keep the dialog window open.

2024-03-31 17:14 UTC, bakicelebi commented on packages/io_library/lib/src/ui/text_input_dialog.dart
> +          style: const TextStyle(color: Colors.black),
Dialog title colors are usually the pocket paint teal color.

2024-03-31 17:14 UTC, bakicelebi commented on packages/io_library/lib/src/ui/text_input_dialog.dart
> +}
I would utilize the GenericDialog for this instead of creating specific ones. Also looks too complicated to me just for a textbox.

2024-05-17 13:00 UTC, msesko commented
Fixed the context.mounted issue by adding a return in the _renameProject in case !context.mounted. Should I throw err there or is return fine @bakicelebi ?

2024-05-31 17:35 UTC, bakicelebi approved these changes
👍🏻

2024-06-01 10:07 UTC, juliajulie95 commented on lib/ui/shared/dialogs/rename_project_dialog.dart
> +              if (!formKey.currentState!.validate()) {
Please don't use null assertion (!)
Do a null check and handle that case

2024-06-01 10:08 UTC, juliajulie95 commented on lib/ui/shared/text_input_field.dart
> +        hintStyle: PaintroidTheme.of(context).textTheme.bodySmall!.apply(
same here with nulll assertion
Also why not make a new style if we need this more often?

2024-06-05 15:08 UTC, merged