PAINTROID-639 Make tool options disappear when tapping the tool
Catrobat/Paintroid-Flutter pull request #46
Opened 2024-01-13 21:06 UTC by Lenkomotive

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

## New Features and Enhancements
- New Features and Enhancements
## Refactorings and Bug Fixes
- Refactorings and Bug Fixes

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-01-15 20:35 UTC, bakicelebi requested changes

2024-01-15 20:35 UTC, bakicelebi commented on lib/ui/drawing_space/bottom_nav_bar.dart
> +  LAYERS,
1 class/widget per file. I believe this is also true for enums.

2024-01-15 20:35 UTC, bakicelebi commented on lib/ui/drawing_space/bottom_nav_bar.dart
> +  void handleToolOptionsVisibility(WidgetRef ref) {
kinda redundant function with 1 line.

2024-01-15 20:35 UTC, bakicelebi commented on lib/ui/drawing_space/tool_options.dart
> +  Column getToolOptions(BuildContext context, WidgetRef ref) {
Please make a widget out of these functions. https://medium.com/@s4.ali/flutter-code-review-dos-and-don-ts-and-best-practices-1-5d003035953e

2024-01-15 20:35 UTC, bakicelebi commented on test/widget/ui/bottom_control_navigation_bar_test.dart
> +      'test if stroke width tool option is invisible when starting app',
There is lots of potential for code deduplication in here that can be added to bottom_nav_bar_interactions.dart

2024-02-03 12:25 UTC, bakicelebi approved these changes
👍🏻

2024-02-07 17:17 UTC, juliajulie95 commented on packages/features/workspace_screen/lib/src/components/bottom_bar/bottom_nav_bar.dart
> +class BottomNavBar extends ConsumerWidget {
I would not extend the ConsumerWidget
Usually you wrap the widget with a Consumer Widget and then you get a variable that is your instance of the reference you need. You can then hand this over to the function.

2024-02-07 17:17 UTC, juliajulie95 commented on packages/features/workspace_screen/lib/src/components/bottom_bar/bottom_nav_bar.dart
> +
Can you please put this under the override function?
overrides should always come first

2024-02-14 13:45 UTC, juliajulie95 approved these changes
Thank you! Good work :)

2024-02-14 13:46 UTC, merged