PAINTROID-490 : Search bar on Landing Page
Catrobat/Paintroid-Flutter pull request #47
Opened 2024-02-08 07:32 UTC by dmdbilal

## New Features and Enhancements
- Added Search functionality for the projects in the landing page.

## Checklist
- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-02-24 13:09 UTC, Lenkomotive commented
@dmdbilal  Hey! Please also add some unit/widget/integration tests. Cheers :)

2024-02-26 15:31 UTC, dmdbilal commented
![image](https://github.com/Catrobat/Paintroid-Flutter/assets/91405690/fb590bc3-cc37-4e06-ac15-32605cfdd221)

2024-02-26 17:08 UTC, juliajulie95 commented
> I'm getting this error all of the sudden. I've tried by cloning the latest version of the project and ran it. There also I'm getting this same error again.
> 
> ![image](https://private-user-images.githubusercontent.com/91405690/307849776-fb590bc3-cc37-4e06-ac15-32605cfdd221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Njc0MTQsIm5iZiI6MTcwODk2NzExNCwicGF0aCI6Ii85MTQwNTY5MC8zMDc4NDk3NzYtZmI1OTBiYzMtY2MzNy00ZTA2LWFjMTUtMzI2MDVjZmRkMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE3MDUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZjMxODVhZWUyMDM4YmMyZmZjYWUzZTM4NTg5NTJjYzcyYzVmZTE1ZWFiMGViYjUxYWRmMGRhMzlkZWYyYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i0suh8F1Zmfqla6-Yrl4qP799KwiGF3Cth-5GOShJmo)

@Lenkomotive Can you help with this? I think it was added in your last ticket?

2024-02-26 17:12 UTC, bhav-khurana commented
I think that's because the current version doesn't support extending the `Path` class as it has only factory constructors

2024-02-26 18:27 UTC, Lenkomotive commented
@bhav-khurana thats correct! @dmdbilal  As @bhav-khurana pointed out, the implementation of `Path` was updated since the version we currently use (3.10.5). Please also downgrade your version too while working on the project. Upgrading to a newer stable version is planned and I believe there is already a ticket. Cheers :)

2024-02-27 15:42 UTC, dmdbilal commented
> @bhav-khurana thats correct! @dmdbilal As @bhav-khurana pointed out, the implementation of `Path` was updated since the version we currently use (3.10.5). Please also downgrade your version too while working on the project. Upgrading to a newer stable version is planned and I believe there is already a ticket. Cheers :)

2024-02-27 15:43 UTC, dmdbilal commented
@Lenkomotive Now it's running without any errors.

2024-03-10 06:15 UTC, dmdbilal commented
@Lenkomotive Added widget test.

2024-03-11 17:55 UTC, juliajulie95 commented
Please add a link to the ticket in your PR description

2024-03-12 15:15 UTC, dmdbilal commented
@juliajulie95 Added the link to the ticket in the PR description.

2024-04-19 15:49 UTC, msesko requested changes
A lot to change. Pls look at it. You cannot just copy code. This makes the whole project unmaintainable

2024-04-19 15:49 UTC, msesko commented on packages/features/landing_page_screen/lib/src/landing_page.dart
> +            icon: const Icon(Icons.search_rounded, color: Colors.white),
please use custom colors we have in light theme. i think: lightColorTheme.onSurface is white color

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/components/image_preview.dart
this is duplicated code? it already exists in landing page screen. you can move that code in the component library and use it in both screen packages

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/components/project_list_tile.dart
duplicated code

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/components/project_overflow_menu.dart
duplicated code

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/search_screen.dart
> +  Future<bool> _loadProject(IOHandler ioHandler, Project project) async {
duplicated functions

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/search_screen.dart
> +  Future<void> _openProject(Project? project, IOHandler ioHandler) async {
duplicated functions

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/lib/src/search_screen.dart
yeah this is pretty much all duplicated. you need to modularize it if it is used in multiple places

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/pubspec.yaml
> +  # Internal packages
all these internal packages are needed?

2024-04-19 15:49 UTC, msesko commented on packages/features/search_bar_screen/pubspec.yaml
> +  intl: ^0.18.0
this is definetly not needed right?

2025-05-15 15:35 UTC, juliajulie95 commented
Closed due to no answer for over a year

2025-05-15 15:35 UTC, closed without merging