PAINTROID-696: If no projects available, create new one when tapping edit icon
Catrobat/Paintroid-Flutter pull request #48
Opened 2024-02-17 22:52 UTC by msesko

Title says it all; If no projects available, create new one when tapping edit icon.

## New Features and Enhancements
- If no projects available, create new one when tapping edit icon.
- + tests
## Refactorings and Bug Fixes
- Nothing new

![Screenshot 2024-02-17 at 23 50 07](https://github.com/Catrobat/Paintroid-Flutter/assets/93492341/5bde16b3-332a-430f-991d-af4bfcfbecb3)

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-02-18 21:22 UTC, bhav-khurana commented
Can we optionally show a `plus` icon instead of the `edit` one for the case when there are no existing projects?

2024-02-19 22:55 UTC, bakicelebi requested changes
@bhav-khurana  Thanks for the great suggestion. I also think that showing plus icon makes more sense instead of edit when there  are no saved project.

2024-02-19 22:55 UTC, bakicelebi commented on packages/features/landing_page_screen/test/widget/landing_page_test.dart
> +
I think it would also be nice if you check if the canvas is clear. Might help in the future to detect regressions.

2024-02-19 22:55 UTC, bakicelebi commented on packages/features/landing_page_screen/test/widget/landing_page_test.dart
> +
Please also add a test for opening a saved project.

2024-02-20 19:13 UTC, msesko commented
> @bhav-khurana Thanks for the great suggestion. I also think that showing plus icon makes more sense instead of edit when there are no saved project.

![image](https://github.com/Catrobat/Paintroid-Flutter/assets/93492341/c961f54a-d4ca-41a8-93c4-87ee3cf7fa96)

Personally I do not like the look of a plus (add) icon in there. Makes it look like a hospital app haha. Tbh I think the pencil icon is also nice for adding. What do you guys think? @bakicelebi @bhav-khurana

2024-02-20 19:58 UTC, bhav-khurana commented
@msesko I would agree.. the plus icon doesn't seem that apt.. The pencil icon looks better imo

2024-02-23 10:13 UTC, bakicelebi commented
The design language is clearer with plus icon because pencil icon can be edit or new, whereas the plus icon is specifically creating something new. Additionally we are also using plus in the bottom right corner for creating a new project. Lets make the UI experience unified :)

2024-02-23 23:18 UTC, msesko commented
> The design language is clearer with plus icon because pencil icon can be edit or new, whereas the plus icon is specifically creating something new. Additionally we are also using plus in the bottom right corner for creating a new project. Lets make the UI experience unified :)

It's ugly tho 😭

2024-02-24 12:06 UTC, Lenkomotive commented
@bhav-khurana Thanks for the suggestion, as @bakicelebi pointed out, it does make the design language clearer. Personally I like the white '+' on grey background more, as it resembles the same design as the current pen icon we use.  :)

2024-02-24 12:42 UTC, bhav-khurana commented
I think we can go with the `+` icon then, it does give that hospital app feeling @msesko :') but it would be more consistent with the app's current design

2024-04-15 17:55 UTC, juliajulie95 commented
please link to jira and resolve conflicts

2024-05-31 22:13 UTC, bakicelebi commented
Is this still a draft?

2024-06-05 15:29 UTC, bakicelebi approved these changes
👍🏻

2024-06-05 15:53 UTC, juliajulie95 approved these changes

2024-06-05 15:53 UTC, merged