Add a placeholder name when saving
Catrobat/Paintroid-Flutter pull request #50
Opened 2024-02-29 00:04 UTC by vishad-tyagi

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

https://catrobat.atlassian.net/browse/PAINTROID-638

Description
If the user saves a project there should be a placeholder in image name like in Piantroid Android.
For the "Save image" dialog, the placeholder should be "image[number]" with the number being the next available number not yet taken in the files.
If I create my first image it should say "image1", when I save this and start a new image it should say "image2".

Same for the projects, here the placeholder should be "project[number]"

## New Features and Enhancements
- New Features and Enhancements
## Refactorings and Bug Fixes
- Refactorings and Bug Fixes

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-03-05 19:01 UTC, vishad-tyagi commented
@juliajulie95 I apologize for the inconvenience. I have identified the issue and am currently implementing a fix.  I added print statements for my self-debugging. I will fix ASAP and commit the changes.

2024-03-05 22:17 UTC, vishad-tyagi commented
@juliajulie95 There is a problem in the unit test case
final textFormField = find.widgetWithText(TextFormField, 'Project name');
      expect(textFormField, findsOneWidget);
      this line in landing_page_test.dart is checking for text Project name but finds autosuggested names like Project1, Project2 etc, which is placeholder names. widgetWithText is very strict with comparing text so a text regex is not a solution. So can I edit this line in this unit test?

2024-03-06 06:33 UTC, juliajulie95 commented
@vishad-tyagi You can definitely change a test if the functionality changed

2024-03-06 07:39 UTC, vishad-tyagi commented
@juliajulie95 ok I will make changes in test case and commit them ASAP

2024-03-06 15:13 UTC, vishad-tyagi commented
@juliajulie95 Kindly check once more, all test cases are passed on my local machine. I have removed the self-debugging print statements

2024-04-15 22:41 UTC, msesko requested changes

2024-04-15 22:41 UTC, msesko commented on packages/io_library/lib/src/service/file_service.dart
> +  // Declare the new methods in the interface
remove comments

2024-04-15 22:41 UTC, msesko commented on packages/io_library/lib/src/service/file_service.dart
> +
perform automatic formatting please

2024-04-21 08:18 UTC, vishad-tyagi commented on packages/io_library/lib/src/service/file_service.dart
> +  // Declare the new methods in the interface
I have removed the comment. 😅

2024-04-21 08:18 UTC, vishad-tyagi commented on packages/io_library/lib/src/service/file_service.dart
> +
😅

2024-04-23 16:12 UTC, Lenkomotive approved these changes

2024-04-29 16:41 UTC, juliajulie95 commented on packages/io_library/lib/src/service/file_service.dart
> +            final num = int.tryParse(match.group(1)!) ?? 0;
Do not use !, null check match.group(1) please

2024-04-30 21:25 UTC, vishad-tyagi commented on packages/io_library/lib/src/service/file_service.dart
> +            final num = int.tryParse(match.group(1)!) ?? 0;
Done!!

2024-05-07 15:07 UTC, juliajulie95 commented
Please resolve conflicts

2024-06-05 16:11 UTC, vishad-tyagi commented
@juliajulie95  Can I continue to contribute even when I am not selected for GSOC ?

2025-10-02 12:58 UTC, juliajulie95 commented
Sure!
Could you resolve the conflicts?

2026-02-05 15:04 UTC, closed without merging