PAINTROID-629: Make bottom view in help dialog dynamically resize-able
Catrobat/Paintroid-Flutter pull request #55
Opened 2024-03-04 23:58 UTC by msesko

[PAINTROID 629](https://jira.catrob.at/browse/PAINTROID-629): Make bottom view in help dialog dynamically resize-able. 

My solution: Expand colored area & change padding for better click-ability

## New Features and Enhancements
- Expand colored area & change padding for better clickability
## Refactorings and Bug Fixes
- Nothing new

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing unit tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Stick to the project’s gitflow workflow
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-03-06 06:36 UTC, juliajulie95 commented
please link to atlassian, not jira

2024-03-06 21:40 UTC, msesko commented
> please link to atlassian, not jira

done

2024-03-09 13:13 UTC, Lenkomotive requested changes
Hey! Instead of just filling in with the same color and "hiding" the problem, please try to find out why the bottom-sheet is not using the entire width.

2024-03-09 18:58 UTC, msesko commented
> Hey! Instead of just filling in with the same color and "hiding" the problem, please try to find out why the bottom-sheet is not using the entire width.

I disagree. It is a UI problem, it was fixed since the user cannot spot a difference anyways. The simplest solution is the best imo.

Regardless I can do the following:

1. wrap the sheet with MediaQuery.removePadding -> did not work for me
2. build a custom bottomSheet and stack it on top of the current content -> introduces a bunch of other things to watch out for like overflows etc.

Is it really necessary to do this? To me changing the background seems the easiest solution. Any solution other than that I tried seems to ignore constraints created by Scaffold. There must surely be a reason why Scaffold does not allow the sheet to span the whole width (reachability)?

2024-03-09 20:15 UTC, Lenkomotive commented
> > Hey! Instead of just filling in with the same color and "hiding" the problem, please try to find out why the bottom-sheet is not using the entire width.
> 
> I disagree. It is a UI problem, it was fixed since the user cannot spot a difference anyways. The simplest solution is the best imo.
> 
> Regardless I can do the following:
> 
> 1. wrap the sheet with MediaQuery.removePadding -> did not work for me
> 2. build a custom bottomSheet and stack it on top of the current content -> introduces a bunch of other things to watch out for like overflows etc.
> 
> Is it really necessary to do this? To me changing the background seems the easiest solution. Any solution other than that I tried seems to ignore constraints created by Scaffold. There must surely be a reason why Scaffold does not allow the sheet to span the whole width (reachability)?

It is not about just finding the simplest solutions, as this is a student project its totally ok to take time and dig deeper into some problems. Thats why I asked you to try to find the actual rootcause. I am aware that the user will see no difference and your solution is simple, yet it will still be unclear for us, why the bottomsheet behaves the way it behaves. 

I tried to research it myself and came up with folllowing: The constrains are set inside the `BottomSheetThemeData` which is inside the `ThemeData`.  Adjusting the constrains there allow us to use the entire width.  Since we have no specified own `ThemeData`, it would be indeed too much work for this ticket, but might be good to consider for the project, as we are facing other issues with BottomSheets.

So, 1 and 2 would have no affect anyway and changing the background is only a workaround imo.

[PAINTROID-703](https://catrobat.atlassian.net/browse/PAINTROID-703)  and [PAINTROID-455](https://catrobat.atlassian.net/browse/PAINTROID-455) are also facing some issues regarding the BottomSheet, maybe its worth to discuss how we can deal with BottomSheets in genreal in the project @bakicelebi @juliajulie95 @exland @bhav-khurana ?

2024-03-11 11:19 UTC, msesko commented
> > > Hey! Instead of just filling in with the same color and "hiding" the problem, please try to find out why the bottom-sheet is not using the entire width.
> > 
> > 
> > I disagree. It is a UI problem, it was fixed since the user cannot spot a difference anyways. The simplest solution is the best imo.
> > Regardless I can do the following:
> > 
> > 1. wrap the sheet with MediaQuery.removePadding -> did not work for me
> > 2. build a custom bottomSheet and stack it on top of the current content -> introduces a bunch of other things to watch out for like overflows etc.
> > 
> > Is it really necessary to do this? To me changing the background seems the easiest solution. Any solution other than that I tried seems to ignore constraints created by Scaffold. There must surely be a reason why Scaffold does not allow the sheet to span the whole width (reachability)?
> 
> It is not about just finding the simplest solutions, as this is a student project its totally ok to take time and dig deeper into some problems. Thats why I asked you to try to find the actual rootcause. I am aware that the user will see no difference and your solution is simple, yet it will still be unclear for us, why the bottomsheet behaves the way it behaves.
> 
> I tried to research it myself and came up with folllowing: The constrains are set inside the `BottomSheetThemeData` which is inside the `ThemeData`. Adjusting the constrains there allow us to use the entire width. Since we have no specified own `ThemeData`, it would be indeed too much work for this ticket, but might be good to consider for the project, as we are facing other issues with BottomSheets.
> 
> So, 1 and 2 would have no affect anyway and changing the background is only a workaround imo.
> 
> [PAINTROID-703](https://catrobat.atlassian.net/browse/PAINTROID-703) and [PAINTROID-455](https://catrobat.atlassian.net/browse/PAINTROID-455) are also facing some issues regarding the BottomSheet, maybe its worth to discuss how we can deal with BottomSheets in genreal in the project @bakicelebi @juliajulie95 @exland @bhav-khurana ?

If we can set constraints in there I suggest to create a custom ThemeData: 

1. create an abstract class PaintroidThemeData
2. create LightPaintroidThemeData that extends PaintroidThemeData so we can also support darkmode in the future
   - in here you define the custom ThemeData and you can also adjust the BottomSheetWidth.

That is how I have done it in previous projects. I have code for this so I can set this up :)

2024-03-11 17:04 UTC, juliajulie95 commented
@msesko Setting up ThemeData sounds good to me! 👍

2024-03-21 08:28 UTC, Lenkomotive commented
> @msesko Setting up ThemeData sounds good to me! 👍

I agree. 👍🏼 This will give us more flexibility in the future dealing with anything related.

2024-03-22 00:30 UTC, msesko commented
> > @msesko Setting up ThemeData sounds good to me! 👍
> 
> I agree. 👍🏼 This will give us more flexibility in the future dealing with anything related.

Yes if you look at the code the bar is already fixed. I just need to match the design to look exactly the same as before.

2024-04-23 14:48 UTC, Lenkomotive requested changes

2024-04-23 14:48 UTC, Lenkomotive commented on packages/component_library/lib/src/theme/data/paintroid_theme_data.dart
> +const dividerThemeData = DividerThemeData(
Why not include this into the abstract calls below?

2024-04-23 14:48 UTC, Lenkomotive commented on packages/component_library/lib/src/theme/data/paintroid_theme_data.dart
> +ElevatedButtonThemeData get buttonThemeData => ElevatedButtonThemeData(
this too...

2024-04-23 14:48 UTC, Lenkomotive commented on packages/component_library/lib/src/theme/state/theme_mode_state_notifier.dart
Please use generated Riverpod

2024-04-23 14:48 UTC, Lenkomotive commented on packages/component_library/lib/src/theme/theme_provider.dart
please use generated Riverpod

2024-04-23 14:48 UTC, Lenkomotive commented on packages/features/onboarding_screen/lib/src/screens/screen2.dart
> +      style: TextStyle(
Consider defining TextStyles for the screens

2024-04-23 16:24 UTC, Lenkomotive approved these changes
👍🏼

2024-05-10 16:43 UTC, merged