PAINTROID-719: Use `.fvmrc` config file as `fvm_config.json` is deprecated
Catrobat/Paintroid-Flutter pull request #58
Opened 2024-03-13 05:59 UTC by bhav-khurana

## Ticket
[PAINTROID-719](https://catrobat.atlassian.net/browse/PAINTROID-719)
## New Features and Enhancements
- Create the `.fvmrc` config file
- Add `.fvm/` directory to gitignore

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing unit tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [x] Stick to the project’s gitflow workflow
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Post a message in the *#paintroid* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2024-03-13 13:19 UTC, msesko commented
Please remove the fvm_config.json from the repo. Just putting ./fmv folder in gitignore wont delete it.

2024-03-13 13:20 UTC, msesko requested changes
Please remove the fvm_config.json from the repo. Just putting ./fmv folder in gitignore wont delete it.

2024-03-16 17:05 UTC, msesko approved these changes
Good

2024-03-24 10:49 UTC, juliajulie95 commented
After installing the new fvm Version and using "fvm install" I get this error:
```
SDK Version : 3.10.5 has Dart SDK 3.0.5 does not meet the project constraints of >=2.17.0 <3.0.0.
This could cause unexpected behavior or issues.
```

I think we should fix that immedeatly.
Please add to your PR so we can get this merged quickly :)
I'm not exactly sure but maybe we can use 
```
environment:
  sdk: ">=3.0.0 <4.0.0"
```

2024-03-24 10:50 UTC, juliajulie95 commented
Oh maybe not, because then I gett errors in the code.
I already created a ticket for flutter update, I'll add it there

2024-03-24 10:53 UTC, juliajulie95 commented
I also now get the error in path_with_action_history.dart.
Even though the flutter version did not change.
Do you have the same?
`Missing concrete implementations of 'Path.addArc', 'Path.addOval', 'Path.addPath', 'Path.addPolygon', and 22 more. `

2024-03-24 11:40 UTC, bhav-khurana commented
> ```
> environment:
>   sdk: ">=3.0.0 <4.0.0"
> ```

I think changing it to `sdk: ">=2.17.0 <3.1.0"` should do the work

2024-03-29 09:39 UTC, juliajulie95 commented
Please add that then :)

2024-04-14 08:56 UTC, juliajulie95 commented on pubspec.lock
> +  dart: ">=3.2.0-194.0.dev <4.0.0"
This cannot be right I think.
When I do fvm flutter pub get it sets this to dart: ">=3.0.5 <3.1.0" which also aligns with what you wrote in the pubspec.yaml file.
Did you update this file too after changing the pubspec.yaml?

2024-05-07 15:06 UTC, juliajulie95 commented
Please resolve conflicts

2024-05-07 15:45 UTC, juliajulie95 commented
changed in another PR

2024-05-07 15:45 UTC, closed without merging