PAINTROID-737: Add Pipette Tool
Catrobat/Paintroid-Flutter pull request #78
Opened 2024-06-06 16:03 UTC by bhav-khurana

## Ticket
[PAINTROID 737](https://catrobat.atlassian.net/browse/PAINTROID-737)

## New Features and Enhancements
As present in the native application, a pipette tool for selecting a particular color from the current state of the drawing canvas is implemented. This tool is a part of the colorpicker package itself and allows the user to pick any color from the drawing and use it on other objects.

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Add the link to the ticket in Jira in the description of the PR
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Make sure to organize imports with 'make sort' before committing
- [x] Confirm that the changes follow the project’s coding guidelines (Wiki)
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Add new information to the [Wiki](https://github.com/Catrobat/Paintroid-Flutter/wiki)

2024-06-07 16:29 UTC, bhav-khurana commented
Hi @juliajulie95 @msesko @bakicelebi 
I have implemented the pipette tool but there is one issue I'm facing that whenever I click on any color in the pipette tool screen and reuse a previous one, it does not match exactly the one that is on the drawing canvas. I am not able to figure out if anything is missing/wrong in the code. Can you please help me out in finding out where exactly the bug might be occurring?

2024-06-13 22:39 UTC, bakicelebi commented
Hi Bhav, I could not reproduce the problem you are having. But i found another similar issue. Transparent colors while drawing are darker. Only after onUp when the command is executed the transparency is correct. And the problem you are describing is happening only when the colors are transparent. I am guessing there is an underlying issue with the color picker and not the pipette tool itself. I will have to have a deeper look but for now few suggestions:

1.  Opening a page should be not necessary. We should keep the same flow as native version of the app. (Instantly selecting the color under the finger)
2. Enable ModalBottomSheet pipette tool  it still defaults to brush tool
3. This is more of an color picker issue but with my specific emulator (small screen size) the apply button is not visible and is very hard to scroll down

![Screenshot_1718318200](https://github.com/Catrobat/Paintroid-Flutter/assets/97812509/b1c755ec-0506-4f00-9d19-c9710fbcbd2a)

2024-06-16 06:26 UTC, bhav-khurana commented
> This is more of an color picker issue but with my specific emulator (small screen size) the apply button is not visible and is very hard to scroll down
For this, should I enable scrolling so that the apply button becomes visible? or reduce the size of each component

2024-06-19 00:23 UTC, bakicelebi commented
> > This is more of an color picker issue but with my specific emulator (small screen size) the apply button is not visible and is very hard to scroll down
> 
> For this, should I enable scrolling so that the apply button becomes visible? or reduce the size of each component

It is already scrollable but it is really hard. I think we should create a new ticket for this and lets discuss how to approach this in the next meeting. @juliajulie95 What do you think?

2024-08-03 13:41 UTC, Lenkomotive requested changes
pls fix conflicts

2024-08-19 12:20 UTC, bhav-khurana commented
@Lenkomotive fixed conflicts

2024-08-23 16:49 UTC, bakicelebi requested changes

2024-08-23 16:49 UTC, bakicelebi commented on packages/colorpicker/lib/pages/pipette_tool_page.dart
> +class PipetteToolPage extends ConsumerStatefulWidget {
Opening a new page for pipette tool is overkill. As mentioned in my previous comment the kotlin version of Pocket Paint doesnt open a new page. You can approach this tool the easiet way:

1. onTap -> get color of the pixel under the point
2. set paint color to that color using paint provider

This simplyfies the user experience and matches the original implementation of the tool and removes alot of unnessary code.

2024-11-21 15:50 UTC, juliajulie95 commented
@bhav-khurana Hi, are you still working on this or should someone take over?

2026-02-05 15:05 UTC, closed without merging