Add Text Tool
Catrobat/Paintroid-Flutter pull request #86
Opened 2024-06-30 16:30 UTC by bhav-khurana

*IN DEVELOPMENT*
## Ticket
[PAINTROID-759](https://catrobat.atlassian.net/browse/PAINTROID-759)
## New Features and Enhancements
Adds the text tool feature as mentioned in the ticket.

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [x] Include the name of the Jira ticket in the PR’s title
- [x] Add the link to the ticket in Jira in the description of the PR
- [x] Include a summary of the changes plus the relevant context
- [x] Choose the proper base branch (*develop*)
- [x] Make sure to organize imports with 'make sort' before committing
- [x] Confirm that the changes follow the project’s coding guidelines (Wiki)
- [x] Verify that the changes generate no compiler or linter warnings
- [x] Perform a self-review of the changes
- [x] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [x] Confirm that new and existing tests pass locally
- [x] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Add new information to the [Wiki](https://github.com/Catrobat/Paintroid-Flutter/wiki)

2024-07-07 15:13 UTC, bhav-khurana commented
Hi @bakicelebi @msesko @juliajulie95 
I have tried adding a basic text tool functionality in the application but I am facing a bit difficulty in debugging some things, can you please check this and help me understand why is the drag in the text field container misbehaving?

2024-07-11 18:24 UTC, bakicelebi commented on lib/core/providers/object/tools/text_tool_provider.dart
> +  }
state = state.copyWith(currentText: text)

2024-07-11 18:24 UTC, bakicelebi commented on lib/core/providers/object/tools/text_tool_provider.dart
> +  }
state = state.copyWith(currentText: text)

2024-07-11 18:26 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/drawing_surface/drawing_canvas.dart
>      return Listener(
if (selectedTool is TextTool) ref.watch(textToolProvider)

2024-07-28 19:47 UTC, bakicelebi commented
This [PR](https://github.com/Catrobat/Paintroid-Flutter/pull/94) has a bounding box implementation that can be useful for text tool aswell. 👍🏻

2024-07-29 18:09 UTC, bhav-khurana commented
Thanks for this, on it

2024-08-19 12:01 UTC, bhav-khurana commented
I have added a basic implementation; can you please review it @bakicelebi @juliajulie95 
there's still a bug though where the text in the drawing canvas does not get immediately updated while writing some text in the text box above. Can you also have a look at the same?

2024-08-23 16:33 UTC, bakicelebi requested changes
Please implement reasonable unit, widget, integration testcases for the new tool.

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_factory/command_factory.dart
> +  AddTextCommand createAddTextCommand(
Should be just `TextCommand` and `createTextCommand`

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_factory/command_factory.dart
> +      AddTextCommand(point, text, style, paint);
Should be just `TextCommand`

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_implementation/add_text_command.dart
> +class AddTextCommand extends GraphicCommand with EquatableMixin {
Should be just `TextCommand`

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_implementation/add_text_command.dart
> +    // TODO
Command dont have undo method or rather should not have one. Please use the override in the specific tool, in this case text tool.

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_implementation/add_text_command.dart
> +  bool? get stringify => true;
why nullable?

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_implementation/add_text_command.dart
> +  @override
This is not the way this project uses serialization. Please have a look at other commands. They are using a version strategy and we should use them in every command.

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/command_manager/command_manager.dart
> +    } else if (command.runtimeType == AddTextCommand) {
Should be `TextCommand`

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/commands/graphic_factory/graphic_factory.dart
> +  static Paint boundingBoxPaint = Paint()
Please merge develop to get the changes from shapes tool PR. There these are already written/implemented

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/providers/object/tools/text_tool_provider.dart
> +  }
Please don't do side effects directly from this provider. Instead wherever you need it use something like this: 
```dart
final textTool = ref.read(toolBoxStateProvider).currentTool as TextTool;
textTool.currentText = newText
```

This was an example I think there should be a new provider to control the text of text tool to update the UI. So the `newText`can be retrieved from that new provider. Maybe a `ShapesToolOptionsStateProvider` ?

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/bounding_box.dart
> +import 'dart:ui';
No need for duplicate file. Original implementation from shapes tool PR can be move to `core\tools`

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +    required this.graphicFactory,
Is not used I think? Can be removed

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +  String? currentText;
is there a reason it being nullable? Can it no be initialized to a default text or simply just ''

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +  Offset? currentPosition;
why is there a need for this when there is a bounding box member.

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +  Paint paint = Paint();
?

2024-08-23 16:33 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +    final rectangleHeight =
Painting text logic can be extracted to a public method and used in command painter

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/bottom_bar/tool_options/text_tool_options.dart
> +            ref.read(textToolProvider.notifier).updateText(newText);
> Please don't do side effects directly from this provider. Instead wherever you need it use something like this: 
```dart
final textTool = ref.read(toolBoxStateProvider).currentTool as TextTool;
textTool.currentText = newText
```

> This was an example I think there should be a new provider to control the text of text tool to update the UI. So the `newText`can be retrieved from that new provider. Maybe a `ShapesToolOptionsStateProvider` ?

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/drawing_surface/canvas_painter.dart
> +    ref.watch(textToolProvider);
Generally no need for `ref.watch(textToolProvider);` You can use the `.repaint()`side effect to trigger a rebuild using `CanvasPainterProvider`

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/drawing_surface/drawing_canvas.dart
> +  final textController = TextEditingController();
I feel like this is misplaced tool specific controller should be in a tool widget. Its not used anyway.

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/drawing_surface/drawing_canvas.dart
> +        child: Stack(
What is this stacking?

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/components/top_bar/top_app_bar.dart
> +        ref.read(toolBoxStateProvider.notifier).switchTool(ToolData.BRUSH);
Why the switch to brush tool?

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/workspace_page.dart
> +        resizeToAvoidBottomInset: false,
Why is this change necessary?

2024-08-23 16:33 UTC, bakicelebi commented on lib/ui/pages/workspace_page/workspace_page.dart
> +  final textController = TextEditingController();
Not used.

2024-08-23 16:38 UTC, bakicelebi commented on lib/core/tools/text_tool/bounding_box.dart
> +  void rotate(Offset point) {}
Pretty sure rotation should be supported by text tool. If this is a technical limitation of your current implementation it should be disabled in some other way, but definetly implemented before merge.

2024-08-23 16:41 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +    paint = paint;
What is the point of this?

2024-08-23 16:43 UTC, bakicelebi commented on lib/core/tools/text_tool/text_tool.dart
> +    final rectangleHeight =
Guides should be drawn after text.

2024-11-21 15:51 UTC, juliajulie95 commented
@bhav-khurana Hi, are you still working on this or should someone take over?

2024-11-22 15:49 UTC, bhav-khurana commented
Hey @juliajulie95
yes it would be great if someone else could do it for now; it will take a while for me to get back to this, sorry for the inconvenience

2025-10-02 12:59 UTC, closed without merging