PAINTROID-736 Implement shapes tool
Catrobat/Paintroid-Flutter pull request #94
Opened 2024-07-25 21:07 UTC by bakicelebi

*Please enter a short description of your pull request and add a reference to the Jira ticket.*

## New Features and Enhancements
- New Features and Enhancements
## Refactorings and Bug Fixes
- Refactorings and Bug Fixes

## Checklist

#### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Paintroid/blob/develop/README.md) and [wiki pages](https://github.com/Catrobat/Catroid/wiki/) of this repository.

- [ ] Include the name of the Jira ticket in the PR’s title
- [ ] Add the link to the ticket in Jira in the description of the PR
- [ ] Include a summary of the changes plus the relevant context
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines (Wiki)
- [ ] Verify that the changes generate no compiler or linter warnings
- [ ] Perform a self-review of the changes
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Confirm that new and existing tests pass locally
- [ ] Check that the commits’ message style matches the [project’s guideline](https://github.com/Catrobat/Catroid/wiki/Commit-Message-Guidelines)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] After the PR, verify that all CI checks have passed
- [ ] Add new information to the [Wiki](https://github.com/Catrobat/Paintroid-Flutter/wiki)

2024-07-29 15:04 UTC, Lenkomotive requested changes
Great work! 

A few things that i noticed while using the app:

1. the width of a shape shrinks with increasing strokeWidth
2. rotating around the anchor while in scale mode makes it hard to position the shape correctly horizontal.
Does it make sense to allow rotation only in when rotation mode is on? And otherwise just scale.
3. When moving the shape, it would be good maybe if possible that the center of the actual shape is not changed. This way the user can click outside the shape to move it without it jumping to the newly clicked position.

If anything is unclear pls feel free to text me!

2024-07-29 15:04 UTC, Lenkomotive commented on test/utils/widget_finder.dart
> +      find.byKey(const ValueKey('circle_shape_type_chip'));
pls add the key to the `WidgetIdentifier` file and use the const value

2024-08-01 20:38 UTC, bakicelebi commented
> 2\. rotating around the anchor while in scale mode makes it hard to position the shape correctly horizontal.
>         Does it make sense to allow rotation only in when rotation mode is on? And otherwise just scale.

This is going to require a lot more changes and I think the the ticket is already to big and complex to review. We should create a separate ticket for this.

2024-08-03 13:31 UTC, Lenkomotive approved these changes

2024-08-04 16:49 UTC, juliajulie95 commented on lib/core/utils/constants.dart
> +const double HALF_PI = 1.5707963267948966;
Würd ich PI / 2 schreiben, also denk PI kann man sicher importen von math oder?

2024-08-04 16:51 UTC, juliajulie95 commented on lib/ui/pages/workspace_page/components/bottom_bar/tool_options/shapes_tool/shapes_tool_shape_type_options.dart
> +                          setState(() {});
Wollen wir statt dem set state noch einen Provider machen?
Ich mein von der performance her wärs okay, weils eh das ganze Widget betrifft, aber weiß net

2024-08-06 14:39 UTC, juliajulie95 commented
Good work, thank you!

2024-08-06 14:40 UTC, merged